### ISSUE TITLE
Chapter 2

### ISSUE THREAD

**Issue by lyvunny** [dogriffiths/HeadFirstAndroid2ndEdition#1]
Hi,

I don't know why my app don't want to run even I have put meticulously the code in Android Studio.

The Hello world App works fine, but once I have replaced the URLs by 
xmlns:android="http://schemas.android.com/apk/res/android" 
xmlns:tools="http://schemas.android.com/tools" 
. . . plus the code for adding the Spinner, the Run App finishes with error.

And I don't know why, the LinearLayout tag is not recognized at all.

I'm using the latest version of Android Studio.

**Comment by croworc** [comment]
Hi @lyvunny, 

could you upload your repo to GitHub (or maybe Google Drive or whatever suits you) and also post the relevant part with the error message from LogCat, please?
Its easier to spot an error directly in the code than guessing from reported symptoms.
Thanks!

**Comment by lyvunny** [comment]
Hi @croworc 
Thanks for your reply. As you can see I'm new in Android dev, then I don't know what is LogCat. Could you elaborate please ? Otherwise I'm going to attach code and screenshots. By the way the code is exactly the same as the book. So I guess I have a problem with my Android Studio Configuration. It's so frustrating because I understand the code in the book but I don't know why it doesn't run. Cheers !

**Comment by dogriffiths** [comment]
Hello,

What error do you get?

DG

**Comment by croworc** [comment]
Hi @lyvunny,
no sweat - we're all somewhat "new" to Android, just because its evolving so fast that once you've learned something, they've already come up with something new, great and shiny, like Architecture Components!
:-)

OK, `Logcat` is the name for Android Studios built-in logging facility/monitor. You'll find the tab for its window panel at the bottom (by default) of the Android Studio "tool window bar":
![androidstudiologcat](https://user-images.githubusercontent.com/12965390/30425229-cb32786e-9948-11e7-9333-8a6ed52d4b56.png)
Here you'll find all the warning-, error-, info-, debug-messages that every running app or Android itself might want to log. You'll learn somewhat later in the book how to make use of it, from within your own apps. It's a really helpful tool!

If your app encounters an error while its running, you'll typically find the stack trace that led to the error here.
In Logcat's upper right corner, you'll find a dropdown box that allows you to filter the source of these log outputs (because typically, there will be quite many, from other running apps as well as from the OS).

When you build and run your project in AS, it should default to "Show only selected application", i.e. your app.
![logcatsourcefilter](https://user-images.githubusercontent.com/12965390/30425658-243364ea-994a-11e7-97d0-57aeeae0523b.png)

Compile time errors, on the other hand, will be spit out by the build system (i.e. Gradle) into the `Messages` window, the tab for which you'll also find by default at the bottom of the tool window bar.
Clicking on an error there will get you into the respective line right in your source code.
![gradlebuilderror](https://user-images.githubusercontent.com/12965390/30426250-9ebc4a64-994b-11e7-9aeb-808e0d1b83e7.png)

Good luck!

**Comment by dogriffiths** [comment]
Could you paste the contents of your layout file here?

**Comment by lyvunny** [comment]
Hi mr Griffiths,

First, even if I'm starting your book, I like it very much. Unfortunately I'm blocked :-)

I'm going to attach here all the informations I can provide, but I'm not at home. Then I'll do it as soon as possible.

Thanks for your interest.

**Comment by lyvunny** [comment]
This my folders . . .
[BeerAdviser.zip](https://github.com/dogriffiths/HeadFirstAndroid2ndEdition/files/1304467/BeerAdviser.zip)
![linearlayout](https://user-images.githubusercontent.com/31954234/30454327-33839198-999c-11e7-918b-2a88f4bc6b49.jpg)
In the linearlayout.jpg we can see AS doesn't recognized LinearLayout
![beer adviser has stopped since you click on run app](https://user-images.githubusercontent.com/31954234/30454584-18fc2456-999d-11e7-9878-979bbd7393a7.jpg)
![messages gradle build](https://user-images.githubusercontent.com/31954234/30454681-6f8c1448-999d-11e7-86c4-548858b8b48a.jpg)
[run message.txt](https://github.com/dogriffiths/HeadFirstAndroid2ndEdition/files/1304517/run.message.txt)
It's Strange. I don't find the logcat . . .

**Comment by lyvunny** [comment]
Finally I've found the logcat
[Logcat.txt](https://github.com/dogriffiths/HeadFirstAndroid2ndEdition/files/1304634/Logcat.txt)

**Comment by lyvunny** [comment]
Ok. Finally I have found the reason why it didn't work. I'm ashamed. I want to hide in a hole. Spinner was incorrectly written. spinner without upper case. AS didn't mention a problem with this tag. That's why I thought it was a different problem until I have discovered logcat thanks to @croworc. Thank you very much @croworc !!!

By the way, I don't understand why LinearLayout was underlined in red, and why for during one moment the urls was not accepted. . . Strange. But it's a happy end.

**Comment by lyvunny** [comment]
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.spinner" in Logcat.

**Comment by croworc** [comment]
@lyvunny 
Good catch! That was certainly difficult, given that you're just starting out with Android **and** Android Studio! Hat Tip!

Btw: Looking at your screen prints, I noticed that you've been working with your layout in folder
  `BeerAdviser/app/build/intermediates/res/merged/debug/layout/activity_find_beer.xml`
This, however, is a path where Gradle will generate *intermediate* files - this isn't the location where you will work with your layout file(s). Generated files will be re-generated upon builds and your changes there would be discarded!
Your layout file(s) are located in:
  `BeerAdviser/app/src/main/res/layout`

On a side note: the current version of Android Studio is:
  `Android Studio 3.0 Beta 5`
Merry coding!
:-)

**Comment by dogriffiths** [comment]
Glad you got it sorted :-). And thanks Ingo!
